### ISSUE TITLE
Add license file

### ISSUE THREAD

**Issue by samherrmann** [lukehoban/go-outline#2]
Luke, can you add a license file to your repo? Since this is a dependency of vscode-go, having a specified license will help the tool approval process for vscode-go in my workplace :)

Can you do the same for [go-find-references](https://github.com/lukehoban/go-find-references)? I would have raised the same issue on that repo, but it looks like the _Issues_ feature is turned off on your fork. Maybe you want to enable that? Thanks!

**Comment by lukehoban** [comment]
This is fixed now in this repo.  

For https://github.com/lukehoban/go-find-references, it is just a minor patch over https://github.com/redefinace/go-find-references which itself doesn't have a LICENSE.    I think it would be best to get a LICENSE added in the root project (and to eventually avoid needing the forked project - it's only there to work around https://github.com/rogpeppe/godef/pull/16).
